Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,38 +1,79 @@
 version: 2.1
-orbs:
-  aws-cli: circleci/aws-cli@0.1.20
-references: 
+
+references:
+
 setup_terraform: &setup_terraform
-  run:
-    name: Setup Terraform
-    command: |
-      curl -O https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
-      curl -O https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_SHA256SUMS
-      terraform_sha256_sum=$(cat terraform_${TERRAFORM_VERSION}_SHA256SUMS | grep linux_amd64)
-      echo $terraform_sha256_sum
-      terraform_sha256_sum_calculated=$(sha256sum terraform_${TERRAFORM_VERSION}_linux_amd64.zip)
-      echo $terraform_sha256_sum_calculated
-      echo "Checking Terraform checksums ..."
-      grep $terraform_sha256_sum_calculated terraform_${TERRAFORM_VERSION}_SHA256SUMS
-      unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d terraform
-      echo 'export PATH=$CIRCLE_WORKING_DIRECTORY/terraform:$PATH' >> $BASH_ENV
+    run:
+      name: Setup Terraform
+      command: |
+        curl -O https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
+        curl -O https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_SHA256SUMS
+        terraform_sha256_sum=$(cat terraform_${TERRAFORM_VERSION}_SHA256SUMS | grep linux_amd64)
+        echo $terraform_sha256_sum
+        terraform_sha256_sum_calculated=$(sha256sum terraform_${TERRAFORM_VERSION}_linux_amd64.zip)
+        echo $terraform_sha256_sum_calculated
+        echo "Checking Terraform checksums ..."
+        grep $terraform_sha256_sum_calculated terraform_${TERRAFORM_VERSION}_SHA256SUMS
+        unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d terraform
+        echo 'export PATH=$CIRCLE_WORKING_DIRECTORY/terraform:$PATH' >> $BASH_ENV
+aws-cli-example: &aws-cli-example
+    - run:
+        name: Install AWS CLI
+        command: |
+          if [ "false" == "false" ] && which aws > /dev/null; then
+            echo "The AWS CLI is already installed. Skipping."
+            exit 0
+          fi
+
+          export PIP=$(which pip pip3 | head -1)
+          if [[ -n $PIP ]]; then
+            if which sudo > /dev/null; then
+              sudo $PIP install awscli --upgrade
+            else
+              # This installs the AWS CLI to ~/.local/bin. Make sure that ~/.local/bin is in your $PATH.
+              $PIP install awscli --upgrade --user
+            fi
+          elif [[ $(which unzip curl | wc -l) -eq 2 ]]; then
+            cd
+            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
+            unzip awscli-bundle.zip
+            if which sudo > /dev/null; then
+              sudo ~/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
+            else
+              # This installs the AWS CLI to the default location (~/.local/lib/aws) and create a symbolic link (symlink) at ~/bin/aws. Make sure that ~/bin is in your $PATH.
+              awscli-bundle/install -b ~/bin/aws
+            fi
+            rm -rf awscli-bundle*
+            cd -
+          else
+            echo "Unable to install AWS CLI. Please install pip."
+            exit 1
+          fi
+    - run:
+        name: Configure AWS Access Key ID
+        command: |
+          aws configure set aws_access_key_id \
+          $AWS_ACCESS_KEY_ID \
+          --profile example
+    - run:
+        name: Configure AWS Secret Access Key
+        command: |
+          aws configure set aws_secret_access_key \
+          $AWS_SECRET_ACCESS_KEY \
+          --profile example
+    - run:
+        name: Configure AWS default region
+        command: |
+          aws configure set region $AWS_DEFAULT_REGION \
+          --profile example
 terraform_init: &terraform_init
   run:
     name: terraform init
     command: |
       source $BASH_ENV
       cd environments/<< parameters.TERRAFORM_ENVIRONMENT >>
-      terraform init    
-
-
-aws-cli-example: &aws-cli-example
-  executor: aws-cli/default
-  steps:
-    - checkout
-    - aws-cli/setup:
-        profile-name: example
-    - run: echo "aws cli setup is done"
-
+      terraform init 
+      
 jobs:
   terraform_plan:
     parameters:
@@ -48,13 +89,10 @@ jobs:
       - checkout
       - *setup_terraform
       - *aws-cli-example
-      - *terraform_init
-
-
+      - *terraform_init        
 workflows:
   version: 2
   aws-cli:
     jobs:
-      - terraform_plan:
-          context: aws
-        
+    - aws-cli-example:
+        context: aws
