Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,21 +1,72 @@
-version: 2
+version: 2.1
+
+references:
+
+aws-cli-example: &aws-cli-example
+    - run:
+        name: Install AWS CLI
+        command: |
+          if [ \"false\" == \"false\" ] && which aws > /dev/null; then
+            echo \"The AWS CLI is already installed. Skipping.\"
+            exit 0
+          fi
+
+          export PIP=$(which pip pip3 | head -1)
+          if [[ -n $PIP ]]; then
+            if which sudo > /dev/null; then
+              sudo $PIP install awscli --upgrade
+            else
+              This installs the AWS CLI to ~/.local/bin. Make sure that ~/.local/bin is in your $PATH.
+              $PIP install awscli --upgrade --user
+            fi
+          elif [[ $(which unzip curl | wc -l) -eq 2 ]]; then
+            cd
+            curl \"https://s3.amazonaws.com/aws-cli/awscli-bundle.zip\" -o \"awscli-bundle.zip\"
+            unzip awscli-bundle.zip
+            if which sudo > /dev/null; then
+              sudo ~/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
+            else
+              This installs the AWS CLI to the default location (~/.local/lib/aws) and create a symbolic link (symlink) at ~/bin/aws. Make sure that ~/bin is in your $PATH.
+              awscli-bundle/install -b ~/bin/aws
+            fi
+            rm -rf awscli-bundle*
+            cd -
+          else
+            echo \"Unable to install AWS CLI. Please install pip.\"
+            exit 1
+          fi
+    - run:
+        name: Configure AWS Access Key ID
+        command: |
+          aws configure set aws_access_key_id \\
+          $AWS_ACCESS_KEY_ID \\
+          --profile example
+    - run:
+        name: Configure AWS Secret Access Key
+        command: |
+          aws configure set aws_secret_access_key \\
+          $AWS_SECRET_ACCESS_KEY \\
+          --profile example
+    - run:
+        name: Configure AWS default region
+        command: |
+          aws configure set region $AWS_DEFAULT_REGION \\
+          --profile example
+
+      
 jobs:
   terraform_plan:
     docker:
-    - image: circleci/python:3.6.1
+      - image: circleci/python:3.6.1
     environment:
-    - AWS_DEFAULT_OUTPUT: json
-    - TERRAFORM_VERSION: 0.12.10
+      AWS_DEFAULT_OUTPUT: json
+      TERRAFORM_VERSION: 0.12.10
     steps:
-    - checkout
-    - run:
-        name: Setup AWS CLI
-        command: |
-          python3 -m venv venv
-          . venv/bin/activate
-          pip3 install -r requirements.txt
+      - checkout
+      - *aws-cli-example
+             
 workflows:
-  version: 2
+  version: 2.1
   aws-cli:
     jobs:
     - terraform_plan:
